# Generated by Django 5.0.6 on 2024-06-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm_categories', '0002_ashpensercategories_category_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ashpensercategories',
            name='category_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ashpensercategories',
            name='category_type',
            field=models.CharField(blank=True, choices=[('Incomes', 'Incomes'), ('Expense', 'Expenses')], max_length=100, null=True),
        ),
    ]
