# Generated by Django 5.0.6 on 2024-06-25 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm_categories', '0003_alter_ashpensercategories_category_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ASHPenserPaymentMethod',
            fields=[
                ('paymethod_data', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(max_length=8)),
                ('paymethod_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ashpenser_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PaymentMethodsData',
                'db_table': 'payment_methods',
                'ordering': ('paymethod_name', 'date_created'),
            },
        ),
        migrations.CreateModel(
            name='ASHPenserSubCategories',
            fields=[
                ('subcategory_data', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(max_length=8)),
                ('subcategory_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategory_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ashpenser_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to=settings.AUTH_USER_MODEL)),
                ('category_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='apm_categories.ashpensercategories')),
            ],
            options={
                'verbose_name_plural': 'SubCategoriesData',
                'db_table': 'subcategories',
                'ordering': ('date_created', 'subcategory_name'),
            },
        ),
    ]
